import streamlit as st

st.set_page_config(
    page_title = "Toolkit",
    initial_sidebar_state = "expanded",
    menu_items={},
    layout="wide"
)

st.title("Interactive Analysis")

st.divider()

st.markdown("You can run analyses to understand how well :blue[users' perceptions of sexism] correspond to different :red[model judgements] and across different forms of sexism.")
st.markdown("Try editing the model below using this dropdown and view results.")

dummy = st.columns(2)
with dummy[0]:
    iv1 = st.selectbox(
            "Choose the model attribute you would like to test",
            ("Perspective_Toxicity", 
            "Perspective_Identity_Attack",
            "Perspective_Insult",
            "Perspective_Profanity",
            "GPT_Sexism"),
            index = 0,
            placeholder=" ",
        )
    c = iv1.split('_')
    model = c[0]
    if (len(c) == 2):
        attr = c[1]
    else:
        attr = "Identity Attack"
with dummy[1]:
    pass

html_option = f"""
<h5 style="text-align: center">User_Rated_Sexism &ensp; ~ &ensp; {iv1} &ensp; + &ensp; Dataset</h5>
<br>
<p style ="text-align:center;font-style:italic">How do user ratings of sexism align with scores of {attr} generated by {model}?</p>
<p style ="text-align:center;font-style:italic">Does it vary for different forms of sexism seen in the data?</p>
"""

st.markdown("");
st.markdown("");
st.markdown("");


st.markdown(html_option, unsafe_allow_html=True)




